trigger: none

pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      yarn
    displayName: 'yarn'

  - script: |
      yarn checkchange
    displayName: 'yarn checkchange'

  - script: |
      yarn build
    displayName: 'yarn build'
